### ISSUE TITLE
Erro às vezes ao salvar número de drinks

### ISSUE THREAD

**Issue by Patrick448** [crepeia/aes#4]
java.lang.NullPointerException
	at aes.service.ChallengeUserFacadeREST.deleteChallenge(ChallengeUserFacadeREST.java:106)

**Comment by Patrick448** [comment]
/aes/webresources/secured/challengeuser/completeCreateChallenge/ - às vezes retorna 400 - bad request
aes/webresources/secured/challengeuser/deleteChallenge/ - às vezes causa erro no servidor (500):

java.lang.NullPointerException
at aes.service.ChallengeUserFacadeREST.deleteChallenge(ChallengeUserFacadeREST.java:106)

**Comment by Patrick448** [comment]
Tentar analisar a possibilidade de mover funcionalidades para o backend.

**Comment by LuanBarbs** [comment]
Resolvido
